apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: umbrella.yaml
    target:
      kind: Application
      name: umbrella
  - path: root-apps.yaml
    target:
      kind: Application
      name: root-apps
