apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coredns-dnssec
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/swipentap/envaapps
    targetRevision: main
    path: manifests/coredns-dnssec
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
