apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: letta
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/swipentap/envaapps
    path: manifests/letta
    targetRevision: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: letta
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
