apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mailu
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://mailu.github.io/helm-charts/
    chart: mailu
    targetRevision: "2"
    helm:
      releaseName: mailu
      valuesObject:
        domain: prod.net
        hostnames:
          - mail.prod.net
        initialAccount:
          enabled: true
          username: admin
          domain: prod.net
          password: ""
          mode: update
        admin:
          extraEnvVars:
            - name: I_KNOW_MY_SETUP_DOESNT_FIT_REQUIREMENTS_AND_WONT_FILE_ISSUES_WITHOUT_PATCHES
              value: "1"
        ingress:
          enabled: true
          className: traefik
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
        front:
          service:
            annotations:
              traefik.ingress.kubernetes.io/service.serversscheme: "https"
              traefik.ingress.kubernetes.io/service.serverstransport: "mailu-front-insecure@kubernetescrd"
  destination:
    server: https://kubernetes.default.svc
    namespace: mailu
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  ignoreDifferences:
  - kind: Ingress
    jsonPointers:
      - /status
