apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mailu-tls
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/swipentap/envaapps
    targetRevision: main
    path: manifests/mailu
  destination:
    server: https://kubernetes.default.svc
    namespace: mailu
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
  ignoreDifferences:
  # Secret can be created by mailu Helm (initialAccount); avoid shared-resource diff with mailu app
  - group: ""
    kind: Secret
    name: mailu-initial-account
    namespace: mailu
