# Deploys enva-umbrella Helm chart (creates child apps).
# Helm values patched per env by overlays.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: umbrella
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://swipentap.github.io/charts
    chart: enva-umbrella
    targetRevision: "1.0.0-190"
    helm:
      values: |
        freeipaChartRevision: "1.0.8-190"
        global:
          env: prod
          domain: prod.net
          tlsSecret: tls-prod-net-wildcard
        mailu:
          nodeHosts: |
            10.11.2.11 k3s-control
            10.11.2.12 k3s-worker-1
            10.11.2.13 k3s-worker-2
            10.11.2.14 k3s-worker-3
        postgresql:
          pgadminHost: pgadmin.prod.net
        sins:
          haproxyIp: "10.11.2.17"
        rancher:
          hostname: rancher.prod.net
        githubRunner:
          group: k3s-prod
          labels:
            - k3s
            - k3s-prod
        freeipa:
          hostname: ipa.prod.net
          realm: PROD.NET
          domain: prod.net
          credentialsSecret: freeipa-credentials
          ingressTlsSecret: tls-prod-net-wildcard
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
