apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coredns-dnssec
  namespace: argocd
spec:
  source:
    targetRevision: dev
    kustomize:
      patches:
        - target:
            kind: ConfigMap
            name: coredns
          patch: |
            - op: replace
              path: /data/NodeHosts
              value: |
                10.11.4.11 k3s-control
                10.11.4.12 k3s-worker-1
                10.11.4.13 k3s-worker-2
                10.11.4.14 k3s-worker-3
