apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: github-runner
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/swipentap/envaapps
    targetRevision: dev
    path: manifests/github-runner-dev
    directory:
      recurse: true
