apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  source:
    helm:
      values: |
        image:
          repository: quay.io/keycloak/keycloak
          tag: "24.0.5"
        command:
        - /opt/keycloak/bin/kc.sh
        - start
        - --optimized
        - --proxy-headers
        - --http-relative-path=/
        extraEnv: |
          - name: KC_PROXY
            value: "edge"
          - name: KC_DB
            value: postgres
          - name: KC_DB_URL_HOST
            value: postgresql-rw.postgresql.svc.cluster.local
          - name: KC_DB_URL_PORT
            value: "5432"
          - name: KC_DB_URL_DATABASE
            value: keycloak
          - name: KC_DB_USERNAME
            value: keycloak
          - name: KC_DB_PASSWORD
            value: keycloak123
          - name: KC_HOSTNAME_STRICT
            value: "false"
          - name: KC_HOSTNAME_STRICT_HTTPS
            value: "false"
        postgresql:
          enabled: false
        ingress:
          enabled: true
          ingressClassName: traefik
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
          hosts:
          - auth.dev.net
          tls:
          - hosts:
            - auth.dev.net
            secretName: tls-dev-net-wildcard
        extraInitContainers: |
          - name: db-init
            image: postgres:15-alpine
            command:
              - /bin/sh
              - -c
              - |
                set -e
                echo "Initializing database and role for Keycloak..."
                
                KEYCLOAK_USER="keycloak"
                KEYCLOAK_PASSWORD="keycloak123"
                DB_NAME="keycloak"
                DB_HOST="postgresql-rw.postgresql.svc.cluster.local"
                DB_PORT="5432"
                POSTGRES_PASSWORD="postgres123"
                
                echo "Waiting for PostgreSQL to be ready..."
                MAX_WAIT=300
                ELAPSED=0
                
                while [ $ELAPSED -lt $MAX_WAIT ]; do
                  if PGPASSWORD="$POSTGRES_PASSWORD" psql -h "$DB_HOST" -p "$DB_PORT" -U postgres -d postgres -c '\q' 2>/dev/null; then
                    echo "PostgreSQL is ready!"
                    break
                  fi
                  echo "Waiting for PostgreSQL... (${ELAPSED}s/${MAX_WAIT}s)"
                  sleep 2
                  ELAPSED=$((ELAPSED + 2))
                done
                
                if [ $ELAPSED -ge $MAX_WAIT ]; then
                  echo "ERROR: Timeout waiting for PostgreSQL"
                  exit 1
                fi
                
                echo "Creating role $KEYCLOAK_USER if it doesn't exist..."
                if ! PGPASSWORD="$POSTGRES_PASSWORD" psql -h "$DB_HOST" -p "$DB_PORT" -U postgres -d postgres -c "SELECT 1 FROM pg_roles WHERE rolname = '$KEYCLOAK_USER';" 2>/dev/null | grep -q 1; then
                  echo "Role does not exist, creating it..."
                  PGPASSWORD="$POSTGRES_PASSWORD" psql -h "$DB_HOST" -p "$DB_PORT" -U postgres -d postgres -c "CREATE ROLE $KEYCLOAK_USER WITH LOGIN PASSWORD '$KEYCLOAK_PASSWORD';" 2>&1 || {
                    echo "ERROR: Failed to create role"
                    exit 1
                  }
                else
                  echo "Role exists, updating password..."
                  PGPASSWORD="$POSTGRES_PASSWORD" psql -h "$DB_HOST" -p "$DB_PORT" -U postgres -d postgres -c "ALTER ROLE $KEYCLOAK_USER WITH PASSWORD '$KEYCLOAK_PASSWORD';" 2>&1 || {
                    echo "ERROR: Failed to update role"
                    exit 1
                  }
                fi
                
                echo "Creating database $DB_NAME if it doesn't exist..."
                if ! PGPASSWORD="$POSTGRES_PASSWORD" psql -h "$DB_HOST" -p "$DB_PORT" -U postgres -d postgres -c "SELECT 1 FROM pg_database WHERE datname = '$DB_NAME';" 2>/dev/null | grep -q 1; then
                  echo "Database does not exist, creating it..."
                  PGPASSWORD="$POSTGRES_PASSWORD" psql -h "$DB_HOST" -p "$DB_PORT" -U postgres -d postgres -c "CREATE DATABASE $DB_NAME OWNER $KEYCLOAK_USER;" 2>&1 || {
                    echo "ERROR: Failed to create database"
                    exit 1
                  }
                else
                  echo "Database already exists"
                fi
                
                echo "Granting all privileges on database $DB_NAME to $KEYCLOAK_USER..."
                PGPASSWORD="$POSTGRES_PASSWORD" psql -h "$DB_HOST" -p "$DB_PORT" -U postgres -d postgres -c "GRANT ALL PRIVILEGES ON DATABASE $DB_NAME TO $KEYCLOAK_USER;" 2>&1 || {
                  echo "ERROR: Failed to grant privileges"
                  exit 1
                }
                
                echo "Database initialization for Keycloak completed successfully!"
