apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  source:
    helm:
      valuesObject:
        ingress:
          rules:
            - host: auth.dev.net
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - auth.dev.net
              secretName: tls-dev-net-wildcard
