apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/swipentap/envaapps
    targetRevision: dev
    path: manifests/keycloak/overlays/dev
    kustomize: {}
