apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mailu
  namespace: argocd
spec:
  source:
    helm:
      valuesObject:
        domain: dev.net
        hostnames:
          - mail.dev.net
        initialAccount:
          domain: dev.net
