apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ollama
  namespace: argocd
spec:
  source:
    helm:
      values: |
        webui:
          ingress:
            enabled: true
            className: traefik
            annotations:
              traefik.ingress.kubernetes.io.router.entrypoints: web,websecure
            tls:
            - hosts:
              - ollama.dev.net
              secretName: tls-dev-net-wildcard
          resources:
            requests:
              memory: "1Gi"
              cpu: "200m"
            limits:
              memory: "3Gi"
              cpu: "1"
        domain: "dev.net"
        subdomain: "ollama"
