apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pgadmin
  namespace: argocd
spec:
  source:
    targetRevision: dev
    path: manifests/pgadmin
    kustomize:
      patches:
        - target:
            kind: Ingress
            name: pgadmin-ingress
          patch: |
            - op: replace
              path: /spec/rules/0/host
              value: pgadmin.dev.net
            - op: replace
              path: /spec/tls/0/hosts
              value:
                - pgadmin.dev.net
            - op: replace
              path: /spec/tls/0/secretName
              value: tls-dev-net-wildcard
