apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
spec:
  source:
    helm:
      valuesObject:
        customPgadmin:
          ingress:
            host: pgadmin.dev.net
            tlsSecretName: tls-dev-net-wildcard
