apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarqube
  namespace: argocd
spec:
  source:
    targetRevision: dev
    path: manifests/sonarqube
    kustomize:
      patches:
        - target:
            kind: Ingress
            name: sonarqube-ingress
          patch: |
            - op: replace
              path: /spec/rules/0/host
              value: sonar.dev.net
            - op: replace
              path: /spec/tls/0/hosts
              value:
                - sonar.dev.net
            - op: replace
              path: /spec/tls/0/secretName
              value: tls-dev-net-wildcard
