apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarqube
  namespace: argocd
spec:
  source:
    helm:
      valuesObject:
        ingress:
          hosts:
            - name: sonarqube.dev.net
          tls:
            - secretName: tls-dev-net-wildcard
              hosts:
                - sonarqube.dev.net
